ALTER TABLE "QuoteItem"
  ADD COLUMN "discount"     DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "taxRate"      DECIMAL(5,2)  NOT NULL DEFAULT 0,
  ADD COLUMN "internalCost" DECIMAL(12,2) NOT NULL DEFAULT 0;
